In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
pd.set_option("display.max_columns",None)

## Lifecycle

* Data Analytics
* Feature Engineering
* Feature Selection
* Model Building
* Model Deployment

Dataset:- https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data

In [47]:
df = pd.read_csv("./datasets/house-prices-advanced-regression-techniques/train.csv")
df.head(8)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,1.5Fin,5,5,1993,1995,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,Wood,Gd,TA,No,GLQ,732,Unf,0,64,796,GasA,Ex,Y,SBrkr,796,566,0,1362,1,0,1,1,1,1,TA,5,Typ,0,NaN,Attchd,1993.0,Unf,2,480,TA,TA,Y,40,30,0,320,0,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,1Fam,1Story,8,5,2004,2005,Gable,CompShg,VinylSd,VinylSd,Stone,186.0,Gd,TA,PConc,Ex,TA,Av,GLQ,1369,Unf,0,317,1686,GasA,Ex,Y,SBrkr,1694,0,0,1694,1,0,2,0,3,1,Gd,7,Typ,1,Gd,Attchd,2004.0,RFn,2,636,TA,TA,Y,255,57,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NWAmes,PosN,Norm,1Fam,2Story,7,6,1973,1973,Gable,CompShg,HdBoard,HdBoard,Stone,240.0,TA,TA,CBlock,Gd,TA,Mn,ALQ,859,BLQ,32,216,1107,GasA,Ex,Y,SBrkr,1107,983,0,2090,1,0,2,1,3,1,TA,7,Typ,2,TA,Attchd,1973.0,RFn,2,484,TA,TA,Y,235,204,228,0,0,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000

In [4]:
df.shape

(1460, 81)

## In Data Analysis we will analyze to find out the below stuff

* Missing Values
* All The Numerical Variables
* Distribution of the Numerical Variables (if it is skewed then we have to do transformation)
* Categorical Variables
* Cardinality of Categorical Variables
* Outliers
* Relationship between independent and dependent feature (SalePrice)

## Missing value

In [5]:
features_with_na = [feature for feature in df.columns if df[feature].isnull().sum() >1]

for feature in features_with_na:
    print(feature," : ", df[feature].isnull().mean() *100)

print("\nTotal Features with null values: ",len(features_with_na))

LotFrontage  :  17.73972602739726
Alley  :  93.76712328767123
MasVnrType  :  0.547945205479452
MasVnrArea  :  0.547945205479452
BsmtQual  :  2.5342465753424657
BsmtCond  :  2.5342465753424657
BsmtExposure  :  2.6027397260273974
BsmtFinType1  :  2.5342465753424657
BsmtFinType2  :  2.6027397260273974
FireplaceQu  :  47.26027397260274
GarageType  :  5.5479452054794525
GarageYrBlt  :  5.5479452054794525
GarageFinish  :  5.5479452054794525
GarageQual  :  5.5479452054794525
GarageCond  :  5.5479452054794525
PoolQC  :  99.52054794520548
Fence  :  80.75342465753424
MiscFeature  :  96.30136986301369

Total Features with null values:  18

In [6]:
# Dropping columns having high % of null values
df1 = df.drop(columns = ["Alley","PoolQC","Fence","MiscFeature"])
features_with_na2 = list1 = [ele for ele in features_with_na if ele not in ["Alley","PoolQC","Fence","MiscFeature"]] 
features_with_na2

['LotFrontage',
 'MasVnrType',
 'MasVnrArea',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [18]:
df1[features_with_na2].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   LotFrontage   1460 non-null   float64
 1   MasVnrType    1452 non-null   object
 2   MasVnrArea    1460 non-null   float64
 3   BsmtQual      1423 non-null   object
 4   BsmtCond      1423 non-null   object
 5   BsmtExposure  1422 non-null   object
 6   BsmtFinType1  1423 non-null   object
 7   BsmtFinType2  1422 non-null   object
 8   FireplaceQu   770 non-null    object
 9   GarageType    1379 non-null   object
 10  GarageYrBlt   1460 non-null   float64
 11  GarageFinish  1379 non-null   object
 12  GarageQual    1379 non-null   object
 13  GarageCond    1379 non-null   object
dtypes: float64(3), object(11)
memory usage: 159.8+ KB

In [8]:
# Can observe mean and median are almost same, and max value are too high
df1[features_with_na2].describe()

       LotFrontage   MasVnrArea  GarageYrBlt
count  1201.000000  1452.000000  1379.000000
mean     70.049958   103.685262  1978.506164
std      24.284752   181.066207    24.689725
min      21.000000     0.000000  1900.000000
25%      59.000000     0.000000  1961.000000
50%      69.000000     0.000000  1980.000000
75%      80.000000   166.000000  2002.000000
max     313.000000  1600.000000  2010.000000

In [9]:
df1["MasVnrArea"].value_counts()

0.0      861
72.0       8
180.0      8
108.0      8
120.0      7
        ...
651.0      1
337.0      1
415.0      1
293.0      1
621.0      1
Name: MasVnrArea, Length: 327, dtype: int64

In [10]:
# For normal distribution replacing with mean values
df1["LotFrontage"] = df1["LotFrontage"].fillna(df1["LotFrontage"].mean())
df1["GarageYrBlt"] = df1["GarageYrBlt"].fillna(df1["GarageYrBlt"].mean())
df1["MasVnrArea"] = df1["MasVnrArea"].fillna(0)
df1[features_with_na2].describe()

       LotFrontage   MasVnrArea  GarageYrBlt
count  1460.000000  1460.000000  1460.000000
mean     70.049958   103.117123  1978.506164
std      22.024023   180.731373    23.994583
min      21.000000     0.000000  1900.000000
25%      60.000000     0.000000  1962.000000
50%      70.049958     0.000000  1978.506164
75%      79.000000   164.250000  2001.000000
max     313.000000  1600.000000  2010.000000

In [11]:
features_with_na3 = [ele for ele in features_with_na2 if ele not in ["LotFrontage","GarageYrBlt","MasVnrArea"]] 

for col in features_with_na3:
    print(col," :\n")
    print(df[col].value_counts())
    print("\n\n")

MasVnrType  :

None       864
BrkFace    445
Stone      128
BrkCmn      15
Name: MasVnrType, dtype: int64



BsmtQual  :

TA    649
Gd    618
Ex    121
Fa     35
Name: BsmtQual, dtype: int64



BsmtCond  :

TA    1311
Gd      65
Fa      45
Po       2
Name: BsmtCond, dtype: int64



BsmtExposure  :

No    953
Av    221
Gd    134
Mn    114
Name: BsmtExposure, dtype: int64



BsmtFinType1  :

Unf    430
GLQ    418
ALQ    220
BLQ    148
Rec    133
LwQ     74
Name: BsmtFinType1, dtype: int64



BsmtFinType2  :

Unf    1256
Rec      54
LwQ      46
BLQ      33
ALQ      19
GLQ      14
Name: BsmtFinType2, dtype: int64



FireplaceQu  :

Gd    380
TA    313
Fa     33
Ex     24
Po     20
Name: FireplaceQu, dtype: int64



GarageType  :

Attchd     870
Detchd     387
BuiltIn     88
Basment     19
CarPort      9
2Types       6
Name: GarageType, dtype: int64



GarageFinish  :

Unf    605
RFn    422
Fin    352
Name: GarageFinish, dtype: int64



GarageQual  :

TA    1311
Fa      48
Gd      14
Po       3
Ex       3
Name: GarageQual, dtype: int64



GarageCond  :

TA    1326
Fa      35
Gd       9
Po       7
Ex       2
Name: GarageCond, dtype: int64

In [12]:
df1[features_with_na3].mode()

,MasVnrType,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond
0,None,TA,TA,No,Unf,Unf,Gd,Attchd,Unf,TA,TA

In [13]:
# Fill null values of categorical column with most probable value
features_with_na4 = ["MasVnrType","FireplaceQu"]
df2 = df1.copy()
for col in features_with_na3:
    if col not in features_with_na4:
        df2[col] = df1[col].fillna(df1[col].mode()[0])
        
df2[features_with_na3].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MasVnrType    1452 non-null   object
 1   BsmtQual      1460 non-null   object
 2   BsmtCond      1460 non-null   object
 3   BsmtExposure  1460 non-null   object
 4   BsmtFinType1  1460 non-null   object
 5   BsmtFinType2  1460 non-null   object
 6   FireplaceQu   770 non-null    object
 7   GarageType    1460 non-null   object
 8   GarageFinish  1460 non-null   object
 9   GarageQual    1460 non-null   object
 10  GarageCond    1460 non-null   object
dtypes: object(11)
memory usage: 125.6+ KB

In [14]:
df2[features_with_na3].mode()

,MasVnrType,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond
0,None,TA,TA,No,Unf,Unf,Gd,Attchd,Unf,TA,TA

In [30]:
# Since it has 2 many null values
df3 = df2.drop(columns = features_with_na4)

In [39]:
df3.isnull().sum().sum()

1

In [40]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 75 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1460 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrArea     1460 non-null   float64
 25  ExterQual      1460 non-null   object
 26  ExterCond      1460 non-null   object
 27  Foundation     1460 non-null   object
 28  BsmtQual       1460 non-null   object
 29  BsmtCond       1460 non-null   object
 30  BsmtExposure   1460 non-null   object
 31  BsmtFinType1   1460 non-null   object
 32  BsmtFinSF1     1460 non-null   int64
 33  BsmtFinType2   1460 non-null   object
 34  BsmtFinSF2     1460 non-null   int64
 35  BsmtUnfSF      1460 non-null   int64
 36  TotalBsmtSF    1460 non-null   int64
 37  Heating        1460 non-null   object
 38  HeatingQC      1460 non-null   object
 39  CentralAir     1460 non-null   object
 40  Electrical     1459 non-null   object
 41  1stFlrSF       1460 non-null   int64
 42  2ndFlrSF       1460 non-null   int64
 43  LowQualFinSF   1460 non-null   int64
 44  GrLivArea      1460 non-null   int64
 45  BsmtFullBath   1460 non-null   int64
 46  BsmtHalfBath   1460 non-null   int64
 47  FullBath       1460 non-null   int64
 48  HalfBath       1460 non-null   int64
 49  BedroomAbvGr   1460 non-null   int64
 50  KitchenAbvGr   1460 non-null   int64
 51  KitchenQual    1460 non-null   object
 52  TotRmsAbvGrd   1460 non-null   int64
 53  Functional     1460 non-null   object
 54  Fireplaces     1460 non-null   int64
 55  GarageType     1460 non-null   object
 56  GarageYrBlt    1460 non-null   float64
 57  GarageFinish   1460 non-null   object
 58  GarageCars     1460 non-null   int64
 59  GarageArea     1460 non-null   int64
 60  GarageQual     1460 non-null   object
 61  GarageCond     1460 non-null   object
 62  PavedDrive     1460 non-null   object
 63  WoodDeckSF     1460 non-null   int64
 64  OpenPorchSF    1460 non-null   int64
 65  EnclosedPorch  1460 non-null   int64
 66  3SsnPorch      1460 non-null   int64
 67  ScreenPorch    1460 non-null   int64
 68  PoolArea       1460 non-null   int64
 69  MiscVal        1460 non-null   int64
 70  MoSold         1460 non-null   int64
 71  YrSold         1460 non-null   int64
 72  SaleType       1460 non-null   object
 73  SaleCondition  1460 non-null   object
 74  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(37)
memory usage: 855.6+ KB

In [43]:
df3["Electrical"].fillna(df3["Electrical"].mode()[0], inplace=True)
df3.isnull().sum().sum()

0

In [46]:
cat_col = df3.select_dtypes(include="O")
len(cat_col.columns)

37